# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 019d7b186ed3a0c973d01a0829ebf396ed1d85555b6c2276f21d71817a709bb491a41840d55e0904e97f6f2e6a8e7636986ae6845b328726c1f15246461c8873

test:
  secret_key_base: b009617f997b9cceca3879d9a1cdac4ff11af5eb5ca478f7e3f04f174d34a0368c517ea53545bcbde264b0a0bd7c10037c6da612d9ca432732548ed57989dc37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
